# Generated by Django 3.2.5 on 2021-07-08 20:33
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [CITextExtension()]
